# Generated by Django 6.0.1 on 2026-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_num", models.CharField(max_length=20)),
                ("client", models.CharField(max_length=20)),
                ("credentials", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=20)),
                ("usage", models.IntegerField()),
            ],
        ),
    ]
