# Generated by Django 6.0.1 on 2026-02-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_serviceaccount_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceaccount",
            name="usage",
            field=models.IntegerField(default=0),
        ),
    ]
